telegram_token: ""

openai_api_key: ""
openai_api_base: null  # leave null to use default api base or you can put your own base url here

novaposhta_api_key: ""
novaposhta_api_url: "https://api.novaposhta.ua/v2.0/json/"

allowed_telegram_usernames: []  # if empty, the bot is available to anyone. pass a username string to allow it and/or user ids as positive integers and/or channel ids as negative integers
new_dialog_timeout: 600  # new dialog starts after timeout (in seconds)
return_n_generated_images: 1
n_chat_modes_per_page: 5
enable_message_streaming: false # if set, messages will be shown to user word-by-word