from core.novaposhta.util.base_response import ResponseObject


class TrackingResponseObject(ResponseObject):
    PossibilityCreateReturn: bool
    PossibilityCreateRefusal: bool
    PossibilityChangeEW: bool
    PossibilityCreateRedirecting: bool
    Number: str
    Redelivery: str
    RedeliverySum: str
    RedeliveryNum: str
    RedeliveryPayer: str
    OwnerDocumentType: str
    LastCreatedOnTheBasisDocumentType: str
    LastCreatedOnTheBasisPayerType: str
    LastCreatedOnTheBasisDateTime: str
    LastTransactionStatusGM: str
    LastTransactionDateTimeGM: str
    LastAmountTransferGM: str
    DateCreated: str
    DocumentWeight: str
    FactualWeight: str
    VolumeWeight: str
    CheckWeight: str
    CheckWeightMethod: str
    DocumentCost: str
    CalculatedWeight: str
    SumBeforeCheckWeight: str
    PayerType: str
    RecipientFullName: str
    RecipientDateTime: str
    ScheduledDeliveryDate: str
    PaymentMethod: str
    CargoDescriptionString: str
    CargoType: str
    CitySender: str
    CityRecipient: str
    WarehouseRecipient: str
    CounterpartyType: str
    AfterpaymentOnGoodsCost: str
    ServiceType: str
    UndeliveryReasonsSubtypeDescription: str
    WarehouseRecipientNumber: str
    LastCreatedOnTheBasisNumber: str
    PhoneRecipient: str
    RecipientFullNameEW: str
    WarehouseRecipientInternetAddressRef: str
    MarketplacePartnerToken: str
    ClientBarcode: str
    RecipientAddress: str
    CounterpartyRecipientDescription: str
    CounterpartySenderType: str
    DateScan: str
    PaymentStatus: str
    PaymentStatusDate: str
    AmountToPay: str
    AmountPaid: str
    Status: str
    StatusCode: str
    RefEW: str
    BackwardDeliverySubTypesActions: str
    BackwardDeliverySubTypesServices: str
    UndeliveryReasons: str
    DatePayedKeeping: str
    InternationalDeliveryType: str
    SeatsAmount: str
    CardMaskedNumber: str
    ExpressWaybillPaymentStatus: str
    ExpressWaybillAmountToPay: str
    PhoneSender: str
    TrackingUpdateDate: str
    WarehouseSender: str
    DateReturnCargo: str
    DateMoving: str
    DateFirstDayStorage: str
    RefCityRecipient: str
    RefCitySender: str
    RefSettlementRecipient: str
    RefSettlementSender: str
    SenderAddress: str
    SenderFullNameEW: str
    AnnouncedPrice: str
    AdditionalInformationEW: str
    ActualDeliveryDate: str
    PostomatV3CellReservationNumber: str
    OwnerDocumentNumber: str
    LastAmountReceivedCommissionGM: str
    DeliveryTimeframe: str
    CreatedOnTheBasis: str
    UndeliveryReasonsDate: str
    RecipientWarehouseTypeRef: str
    WarehouseRecipientRef: str
    CategoryOfWarehouse: str
    WarehouseRecipientAddress: str
    WarehouseSenderInternetAddressRef: str
    WarehouseSenderAddress: str
    CounterpartySenderType: str
    AviaDelivery: str
    BarcodeRedBox: str
    CargoReturnRefusal: str
    DaysStorageCargo: str
    Packaging: str
    PartialReturnGoods: str
    SecurePayment: str
    PossibilityChangeCash2Card: bool
    PossibilityChangeDeliveryIntervals: bool
    PossibilityTermExtensio: bool
    StorageAmount: str
    StoragePrice: str
    FreeShipping: str
    LoyaltyCardRecipient: str
